---
title: "Codebook"
output: html_notebook
---

First, read both of the training and testing tables

xtrain <- read.table(file.path(dataFile, "train/X_train.txt"))
ytrain <- read.table(file.path(dataFile, "train/y_train.txt"))
subject_train <- read.table(file.path(dataFile, "train/subject_train.txt"))

xtest <- read.table(file.path(dataFile, "test/X_test.txt"))
ytest <- read.table(file.path(dataFile, "test/y_test.txt"))
subject_test <- read.table(file.path(dataFile, "test/subject_test.txt"))

Then, merge the tables

mrg_train <- cbind(ytrain, subject_train, xtrain)
mrg_test <- cbind(ytest, subject_test, xtest)
data_all <- rbind(mrg_train, mrg_test)

Set a subject of all the mean and standard deviation

mean_std <- (grepl("activityID", col_Names) | grepl("subjectID", col_Names) | grepl("mean.", col_Names) | grepl("std.", col_Names))

Uses descriptive activity names to name the activities in the data set

names_activities <- merge(sub_mean_std, activityLabels, by = "activityID", all.x = TRUE)
levels(names_activities$activityID) <- c("WALKING", "WALKING UPSTAIRS", "WALKING DOWNSTAIRS", "SITTING", "STANDING", "LYING")
names(names_activities) <- gsub("^t", "Time", names(names_activities))
names(names_activities) <- gsub("^f","Frequency", names(names_activities))
names(names_activities) <- gsub("Acc","Accelerometer", names(names_activities))
names(names_activities) <- gsub("Gyro","Gyroscope", names(names_activities))
names(names_activities) <- gsub("Mag","Magnitude", names(names_activities))
names(names_activities) <- gsub("BodyBody","Body", names(names_activities))
names(names_activities) <- gsub("tBody","TimeBody", names(names_activities))
names(names_activities) <- gsub("angle","Angle", names(names_activities))
names(names_activities) <- gsub("gravity","Gravity", names(names_activities))
names(names_activities) <- gsub("-mean()",".Mean", names(names_activities))
names(names_activities) <- gsub("-std()",".STD", names(names_activities))
names(names_activities) <- gsub("-freq()",".Frequency", names(names_activities))

Create a second, independent tidy data set with the average of each variable for each activity and each subject

secTidyData <- names_activities %>% group_by(subjectID, activityID) %>% summarise(across(everything(), mean))

Save data as text file

write.table(secTidyData, "secTidyData.txt", row.names = FALSE)
